### ISSUE TITLE
Three.js compatibility

### ISSUE THREAD

**Issue by adishavit** [mattdesl/fontpath#2]
Can I output a js[on] file that is compatible with the files generated by typeface.js so they can be used without modifications in three.js?

**Comment by mattdesl** [comment]
No; although you could write a stream that takes in the "fontpath" JSON and pipes it to a "typefacejs" JSON. I have no plans to support TypefaceJS since that is very dated.

**Comment by adishavit** [comment]
Thanks. So what `fontpath` tools will allow me to achieve the following functionality with minimal modifications:
1. Take a string of text (more than 1 glyph)
2. Select a font (either load the font file or the json from fontpath)
3. Convert the string to a 2D vector representation with the font. Useful formats would be:
   1. SVG
   2. Something easily convertible to THREE.Shape.

Thanks!

**Comment by mattdesl** [comment]
Unfortunately these tools are not really stable enough for that kind of high-level use. 

You can grab the vector outline of the fonts like so:

`fontpath Foobar.ttf --size 32 > Foobar.json`

But then you still have a lot of steps ahead of you, e.g.
- decompose curves into discrete polyline contours
- triangulate polylines (earcut, poly2tri or tess2)
- layout & word-wrapping

There are some scattered "fontpath" related modules for this but they are still highly experimental and not robust enough for production use.

If you want nice text rendering in ThreeJS I would suggest SDF rendering rather than vector outlines. It tends to be easier to set up and render, and has a lot more potential for effects. There are a growing number of tools related to SDF and bitmap font rendering, and some of them are already being used in production. 

https://github.com/Jam3/three-bmfont-text
https://github.com/mattdesl/text-modules

**Comment by adishavit** [comment]
Actually I need to extrude the text glyph (or some other 3D manipulations), so I need the actual curves (+ triangulations).  

The [shape2D-triangulate](https://github.com/mattdesl/shape2d-triangulate) project seems to do almost what I need except that it works only on a single glyph. How would I use that technique for more than one character (taking into account the font's natural kerning)?  

Alternatively, maybe I could take the [fontpath-simple-renderer](https://github.com/mattdesl/fontpath-simple-renderer) approach and render to an SVG (I have an SVG to three.js shape converter)? What would that require?

**Comment by mattdesl** [comment]
K, in that case you can use:
- fontpath to generate a JSON font
- fontpath-simple-renderer to lay out and word-wrap some text from JSON font
- fontpath-shape2d to convert a single glyph (SVG-like path data) into discrete polylines
- shape2d-triangulate to triangulate a set of polylines with holes

For an implementation example (not in ThreeJS) you could see here: 
https://github.com/mattdesl/fontpath-gl

Also if you find the triangulation/curve approximation are giving you problems, you could swap those out with other modules like:
- [earcut](https://www.npmjs.com/package/earcut) or [triangulate-contours](https://www.npmjs.com/package/triangulate-contours)
- [adaptive-bezier-curve](https://www.npmjs.com/package/adaptive-bezier-curve)

**Comment by adishavit** [comment]
Great! Thanks, I'll give that a shot!

**Comment by mattdesl** [comment]
P.S. Apologies if this seems a bit hap-hazard. :smile: I have learned a great deal about modularity since writing these, and I'm slowly moving the "fontpath" code into more robust and isolated modules. e.g. [word-wrapper](https://www.npmjs.com/package/word-wrapper) instead of [fontpath-wordwrap](https://github.com/mattdesl/fontpath-wordwrap).

**Comment by adishavit** [comment]
No need to apologize. I'm still learning the right way to structure JS code
myself.
Thank you very much for your efforts and help!
